# 默认配置文件，部分参数可以修改，但注意是否正确，否则报错
global:
  bbox_type: &bbox_type "xywh"
  map_path: &map_path "data/map/JiuLongLake_v0109/mesh.obj" #可更换地图
  offset: &offset "data/map/JiuLongLake_v0109/offset.txt" #随地图变化,很重要
  time_slice: &time_slice 1000 # 时间线融合, 可以调整, 单位ms
  enable_reloaction: &enable_reloaction False # 默认，不可修改
  order: &order "rzyx" # 固定参数
  exit_key: "e" # 退出按键,留给用户自定义  内置有esc q Q 三个按键

pipeline:
  stage1:
    idx: 1
    name: "MQTTSource"
    parallel: 1
    args:
      offset: *offset
      bbox_type: *bbox_type
      broker_url: "192.168.31.210" # mqtt  服务器地址
      port: 1883 #mqtt服务端口
      client_id: "sub_camera_param" # 客户端ID，保证唯一
      qos: 2 #服务质量
      topic_uav_sn: "thing/product/sn" # sn订阅话题
      timeout: 30 # mqtt连接超时限制

  stage2:
    idx: 2
    name: "MOTracker"
    parallel: 1
    args:
      max_age: 20 # 遗忘时间
      min_hits: 4 # 最小匹配次数
      distance_threshold: 10 # 距离阈值
      max_queue_length: null

  stage3:
    idx: 3
    parallel: 1
    name: "TimeFilter"
    args:
      time_slice: *time_slice
      max_queue_length: null

  stage4:
    idx: 4
    parallel: 4  # 并行数，根据机器性能调整
    name: "EstiPosition"
    args:
      map_path: *map_path
      default_height: 60 #默认平面
      order: *order
      enable_reloaction: *enable_reloaction
      max_queue_length: null

  stage5:
    idx: 5
    name: "SpatialFilter"
    parallel: 1
    args:
      time_slice: *time_slice
      distance_threshold: 10.0 #多机融合距离阈值，两个目标不可以长时间在这个距离内相
      max_map: 100
      max_queue_length: null

  stage6:
    idx: 6
    parallel: 1
    name: "HttpSink"
    args:
      url: "http://192.168.31.31:8888/jk-ivas/non/controller/postTarPos.do" # 下游接口地址
      offset: *offset
      max_retries: 5 # 错误重发次数

