global:
    bbox_type: &bbox_type "xywh"
    map_path: &map_path "data/map/JiuLongLake_v1223/mesh.obj"
    offset: &offset "data/map/JiuLongLake_v1223/offset.txt"
    time_slice: &time_slice 100
    enable_reloaction: &enable_reloaction False
    order: &order "rzyx"

pipeline:
  # stage1:
  #   name: "JsonSource"
  #   args:
  #     file_path: "simulated_data/simulate_data.json"
  #     bbox_type: "cxcywh"

  stage1:
    name: "MQTTJsonSource"
    args:
        offset: *offset
        bbox_type: *bbox_type
        file_path: "data/1703252135_TH7923461373.json"

  # stage1:
  #   name:  "UDPSource"
  #   args:
  #       ip: "127.0.0.1"
  #       port: 8888

  # stage1:
  #   name:  "MQTTSource"
  #   args:
  #       offset: *offset
  #       bbox_type: *bbox_type
  #       broker_url: "192.168.31.210"
  #       port: 1883
  #       client_id: 'sub_camera_param'
  #       qos: 2
  #       topic_uav_sn: "thing/product/sn"
  #       timeout: 30

  stage2:
    name: "TimeFilter"
    args:
      time_slice: *time_slice
      max_queue_length: null

  stage3:
    name: "EstiPosition"
    args:
      map_path: *map_path
      default_height: 60
      order: *order
      enable_reloaction: *enable_reloaction
      max_queue_length: null

  stage4:
    name: "SpatialFilter"
    args:
      time_slice: *time_slice
      distance_threshold: 10.0
      max_map: 10
      max_queue_length: null

  # stage5:
  #   name:  "UnitySink"
  #   args:
  #       ip:   "127.0.0.1"
  #       port_file: "../port.txt"
  #       max_retries: 5

  # stage5:
  #   name:  "HttpSink"
  #   args:
  #      url: "http://192.168.31.31:8888/jk-ivas/non/controller/postTarPos.do"
  #      offset: *offset
  #      max_retries: 5

  stage5:
    name: "PrintSink"
    args:
      time_freq: 10
      offset: *offset
